version: '3.3'

services:
  server:
    container_name: etica-auth
    image: "node:14.5.0"
    working_dir: /home/node/auth
    command: "yarn auth:start"
    ports:
      - "5000:5000"
    volumes:
      - ./packages/auth:/home/node
  app:
    container_name: etica-app
    image: "node:14.5.0"
    working_dir: /home/node/app
    command: "yarn app:start"
    ports:
      - "3000:3000"
    volumes:
      - ./packages/app:/home/node
