version: '3.3'

services:
  app:
    container_name: etica-app
    image: "node:14.5.0"
    working_dir: /home/node/app
    command: "yarn start"
    ports:
      - "3000:3000"
    volumes:
      - .:/home/node
